### ISSUE TITLE
allow the backing array to be generic over different array sizes

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/tinyvec#10]
this probably won't be const generics, just some sort of trait bound for a sealed trait on specific array sizes, such as 0 to 32, as well as powers of 2 up to 4096, also 33 probably just because it's 1 better.

**Comment by Shnatsel** [comment]
Alternatively you can put the entire library in a macro that accepts the backing type and instantiate the implementation for every length and type combination that is used

**Comment by Lokathor** [comment]
while technically possible, that usually leads to a poor editor experience with current RLS abilities.

**Comment by Shnatsel** [comment]
If you're using RLS, you're gonna have a bad time. I'm not confident rust-analyzer handles this well, though.

**Comment by Lokathor** [comment]
I use RLS, that's the official tool to use! ;_;

**Comment by Lokathor** [comment]
Done in 0.1, at least enough to close this for now.
