### ISSUE TITLE
Make code DRYer

### ISSUE THREAD

**Issue by Soveu** [Lokathor/tinyvec#101]
Most of TinyVec code looks like this
```rust
pub fn whatever(self, args) -> ReturnType {
  match self {
    Self::Inline(i) => i.whatever(args),
    Self::Heap(h) => h.whatever(args),
  }
}
```

While coding TInyBitVec I made [a macro that produces this kind of code automatically](https://github.com/Soveu/tinybitvec/blob/master/src/tinybitvec.rs)

If we are interested, I could port it here

**Comment by Lokathor** [comment]
yeah that seems useful
