### ISSUE TITLE
Replace `A: Default` bounds by a constructor on `Array`

### ISSUE THREAD

**Issue by Nemo157** [Lokathor/tinyvec#111]
At the moment there are some types like `TinyVec<[u8; 64]>` which are usable, but don't support every operation, e.g. `TinyVec::new()` or `impl Deserialize for ArrayVec<[u8; 64]>`, because these operations need to be able to construct an "empty" array.

Since there's already the `Array` trait which is used to abstract over the inline storage, this trait could have a "default constructor" added to it, replacing the `A: Default` bounds in places, and ensure exactly the same set of arrays are usable as the backing storage as are default constructable (and this bypasses the const-generics questions around `Default` because of `impl T Default for [T; 0]` that may block having generalized array `Default` in `std` anytime soon, `Array` can just not have that inconsistent impl).

**Comment by Lokathor** [comment]
I don't follow. What would the default constructor be that would be generic across all types?

like each impl would just declare a default constructor and write out [A::default()] however many times is needed?

**Comment by Nemo157** [comment]
> like each impl would just declare a default constructor and write out [A::default()] however many times is needed?

Or `[A::default(); N]` I think would work, which should fit into the existing macro implementations.

**Comment by Lokathor** [comment]
I think that would require a Copy bound.

But since we dont even add impls of Array often we can have a script just spit it out.
