### ISSUE TITLE
Very long build times in release

### ISSUE THREAD

**Issue by zeroflaw** [Lokathor/tinyvec#115]
I've recently update to version 1.0.0 and found tinyvec as the cause of some extremely long build times (Release only) (0.4.1 = 10 seconds, 1.0.0 = 1 hours)

seems to have something to do with code using ArrayVec the larger the ArrayVec the longer the build time. It seems to also depend on the size of the object as well.  I can't post all the code here because it very large, I'll try cut out a minimal example to demonstrate.
`
MAX_POSITIONS = 200
pub fn new() -> Self {
        PositionUpdateArray(ArrayVec::<[PositionUpdate; MAX_POSITIONS]>::from_array_len(
            [PositionUpdate::DEFAULT; MAX_POSITIONS],
            0,
        ))
    }`

Other useful information:
MacOSX
rustc 1.48.0-nightly (397b390cc 2020-08-27) 
Debug mode is unaffected, only release mode

**Comment by Lokathor** [comment]
how big is a PositionUpdate value?

**Comment by zeroflaw** [comment]
It contains several rust_decimal::Decimal (which don't seem to be a problem)
some custom structs that contains static str and enums (which do seem to be the cause) 

I'll try put together a minimal example.

**Comment by Lokathor** [comment]
and with a length of 200, i presume that you're using const generics in here also?

**Comment by zeroflaw** [comment]
yes I am using the feature nightly_const_generics

**Comment by Lokathor** [comment]
Possibly related: https://github.com/rust-lang/rust/issues/54540

**Comment by saethlin** [comment]
I've been routinely compiling my benchmark suite with const generics and an array length of 256, and I can confirm it doesn't take an hour to build. At 18 seconds for the compilation of the benchmark binary itself it's not exactly speedy, but I don't think this issue is still a problem.

**Comment by Lokathor** [comment]
Alright. Another issue can be created if this comes up again, closing for now.
