### ISSUE TITLE
The `array_vec!` macro does not support the array-like `[T; N]` syntax you'd generally expect it to

### ISSUE THREAD

**Issue by slightlyoutofphase** [Lokathor/tinyvec#117]
Not a huge deal, but certainly something people might view as what is often called a "papercut" in the Rust community, as that syntax is supported by at least regular `vec!` and `smallvec!` as far as "Very Popular Data Structures™" go, and even in `staticvec` supporting it kind of just seemed like an immediate "must have" to me from day one.  
  
The entire implementation of the `staticvec!` macro is just this, if it helps at all:  
  
```rust
macro_rules! staticvec {
  ($($val:expr),* $(,)*) => {
    $crate::StaticVec::new_from_const_array([$($val),*])
  };
  ($val:expr; $n:expr) => {
    $crate::StaticVec::new_from_const_array([$val; $n])
  };
}
```

**Comment by Lokathor** [comment]
At a glance, this looks backwards compatible. If it turns out to be, we should add it for sure.
