### ISSUE TITLE
please add license texts for MIT and Apache-2.0 licenses

### ISSUE THREAD

**Issue by decathorpe** [Lokathor/tinyvec#119]
According to Cargo.toml and its git history, the project was relicensed from `Zlib` to `Zlib OR MIT OR Apache-2.0`, but only the license text for the Zlib license is included. Both the MIT and the Apache 2.0 license require that their license texts accompany source code (so as far as I know, your argument for just not including the MIT license text to circumvent this is not correct).

The missing license texts are an issue for downstream projects (for example, the package for this project in linux distributions), so please consider adding them.

See: https://choosealicense.com/licenses/mit/ and https://choosealicense.com/licenses/apache-2.0/ (hovering the "License and copyright notice" condition shows what I'm referring to)

**Comment by Lokathor** [comment]
As you say, I was told by @JoshTripplet that it's valid to not include any license text and then users will have "automatically" included the text because there's nothing to include. They may want to weigh in.

Otherwise, sure, we can add the files.

**Comment by Lokathor** [comment]
oops, @JoshTriplett is the correct spelling.

I'll start the PR i suppose

**Comment by joshtriplett** [comment]
It's entirely valid to license a project under those licenses, using the SPDX identifiers in Cargo.toml, and not include the text. The legal requirement is to preserve the text of present, not to add it if not present. Distributions do not need to add it. They could choose to, but they don't need to.

**Comment by Lokathor** [comment]
Closed in #120

**Comment by decathorpe** [comment]
Thank you!
