### ISSUE TITLE
`From<&'_ [T]>` implementation for ArrayVec.

### ISSUE THREAD

**Issue by msmorgan** [Lokathor/tinyvec#133]
It would be useful to me to have such an implementation, or else a method that specifically writes a slice to a new ArrayVec.

**Comment by Lokathor** [comment]
i could probably accept a PR for this if it doesn't conflict with any of the other From impls (there's a few already).

In the meantime I think you can probably do this with
`slice.iter().collect()`

**Comment by msmorgan** [comment]
Should it truncate the slice to its storage length, or would it be preferable to panic if the slice is too long?

**Comment by Lokathor** [comment]
i *think* the other impls overflow and panic, so the from impl should do the same.

**Comment by paolobarbolini** [comment]
> **Note: This trait must not fail.** If the conversion can fail, use [TryFrom](https://doc.rust-lang.org/stable/std/convert/trait.TryFrom.html).

Taken from the docs for [From](https://doc.rust-lang.org/stable/std/convert/trait.From.html)

This should probably be like the implementation for `slice` into fixed size `array` (see [here](https://doc.rust-lang.org/stable/std/convert/trait.TryFrom.html#impl-TryFrom%3C%26%27_%20%5BT%5D%3E))

**Comment by Lokathor** [comment]
Ah, excellent. Yeah, then TryFrom should be used.
