### ISSUE TITLE
Pretty-print Debug format option

### ISSUE THREAD

**Issue by mb64** [Lokathor/tinyvec#137]
`tinyvec::TinyVec` has a different `Debug` pretty-print format to `std::vec::Vec` (and to the slice pretty-print format).

Example code:

```rust
use tinyvec::{tiny_vec, TinyVec};

fn main() {
    let xs: Vec<i32> = vec![1, 2, 3];
    println!("Vec: {:#?}", xs);

    let xs: TinyVec<[i32; 6]> = tiny_vec![1, 2, 3];
    println!("TinyVec: {:#?}", xs);
}
```
Output:
```
Vec: [
    1,
    2,
    3,
]
TinyVec: [1, 2, 3]
```
Expected output:
```
Vec: [
    1,
    2,
    3,
]
TinyVec: [
    1,
    2,
    3,
]
```
[Playground link.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5e6020aaf95e673d253caf9381977309)

This is also the format used by the `dbg!` macro, which is where I originally noticed the difference.

**Comment by Soveu** [comment]
[It looks like tinyvec has its own Debug impl](https://github.com/Lokathor/tinyvec/blob/main/src/tinyvec.rs#L1322)
If you use `as_slice()` then the debug pretty-print looks as expected

**Comment by Lokathor** [comment]
A pr to make the tinyvec types use the alternate format flag would be acceptable.

**Comment by Soveu** [comment]
I'm working on it now
