### ISSUE TITLE
New release for arbitrary functionality

### ISSUE THREAD

**Issue by jeffa5** [Lokathor/tinyvec#147]
Is it possible to have a new release with the functionality from https://github.com/Lokathor/tinyvec/pull/146 in?

**Comment by Lokathor** [comment]
Yeah, but I just left my main computer. Can you do a PR for the changelog entry?

**Comment by jeffa5** [comment]
Sure https://github.com/Lokathor/tinyvec/pull/148

**Comment by Lokathor** [comment]
1.3 is out!
