### ISSUE TITLE
Is there a way to use #![feature(generic_const_exprs)] with ArrayVec?

### ISSUE THREAD

**Issue by dorianprill** [Lokathor/tinyvec#156]
I am using ArrayVec for calculating roots of splines, which is very ergonomic since there are only up to a certain number of them.

Normal consts work with ArrayVec e.g. for a cubic spline I can have a method:

```
fn real_roots_cubic(&self, axis: usize) -> ArrayVec<[P::Scalar; 3]> {
    let mut result = ArrayVec::new();
    ...
}
```

I can't figure out how to get the generic case working though, especially where I require an expression.  
For example: for a generic bezier curve the type is:

```
pub struct Bezier<P, const N: usize>
where
    P: Point,
{ 
    control_points: [P; N]
}
```

But if I change the signature accordingly, I always get an error  ` the trait Array is not implemented for [<P as point::Point>::Scalar; _]`.  

```
fn real_roots(&self, axis: usize) -> ArrayVec<[P::Scalar; N-1]> {
    let mut result = ArrayVec::new();
    ...
}
```
I couldn't find any info on it in the documentation or in the repo. It works with regular rust arrays if you enable #![feature(generic_const_exprs)]

Anyway, I love this crate!

edit: some corrections; I cant get it working with just N as array size either, same error

**Comment by Soveu** [comment]
I think you are not using the `rustc_1_55` feature, which enables `ArrayVec` for all the `const N: usize`

**Comment by dorianprill** [comment]
Your suggestion worked, thanks! 
Meanwhile found it in Cargo.toml but not in the docs. Will close
