### ISSUE TITLE
Add try_reserve and similar functions to TinyVec

### ISSUE THREAD

**Issue by i509VCB** [Lokathor/tinyvec#157]
This should allow growing a TinyVec to have an allocation error caught if there is array overflow. 

This feature will probably need to be feature gated with a new `rust_1_57` feature since these functions are relatively new.

**Comment by Lokathor** [comment]
Good plan

**Comment by i509VCB** [comment]
Well github didn't close the issue

**Comment by Lokathor** [comment]
I think you have to put "Closes #IssueNum" on a line of its own for github to detect and auto-close an issue when a PR merges.
