### ISSUE TITLE
"unsatisfied trait bounds" for `N` > 33?

### ISSUE THREAD

**Issue by schubart** [Lokathor/tinyvec#169]
```rust
    let some_ints = ArrayVec::<[usize; 33]>::new();
    let more_ints = ArrayVec::<[usize; 34]>::new();
```

gives

```
error[E0599]: the function or associated item `new` exists for struct `ArrayVec<[usize; 34]>`, but its trait bounds were not satisfied
  --> src/main.rs:19:46
   |
19 |     let more_ints = ArrayVec::<[usize; 34]>::new();
   |                                              ^^^ function or associated item cannot be called on `ArrayVec<[usize; 34]>` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `[usize; 34]: Array`

For more information about this error, try `rustc --explain E0599`.
```

Why does it compile for 33 but not for 34? What's the significance of 33 and 34? 

(Rust 1.65.0, `tinyvec` 1.6.0.)

**Comment by schubart** [comment]
I now found https://docs.rs/tinyvec/latest/tinyvec/trait.Array.html and understood that not all N are supported, unless you use the `rustc_1_55` feature. This fixed the compile error.

I think this deserves a more prominent mention on the documentation front page. I'd imagine that most new users of the crate will be tripped up by this.

**Comment by Lokathor** [comment]
Ah, we could document this better.

The traits are only implemented for up to 32 unless the min const generics stuff is used, which is what the rustc_1_55 is mostly turning on.
