### ISSUE TITLE
Proposal: Rolling MSRV, Stable-N

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/tinyvec#174]
Currently the readme says "Min Rust 1.34", and the CI is for 1.34, but there's no particularly strong statement that the MSRV will never move.

I'm proposing that we bump the MSRV slowly over time to avoid too many verson-compat features getting in, and avoid having too many differences across versions.

Currently there's no pressure for immediate new features, but I'd like to try and sort this out *before* any such pressure does arise.

Since we're already *more* than 20 versions behind Stable, we could have "Stable -20" as the support range. That's quite a but more than any other Rust crate, so I can't imagine many concerns.

**Comment by striezel** [comment]
The current stable version of Rust is 1.67.0 (released on 2023-01-26), so it could even be "Stable-30" at the moment. So why not use that as the support range? This should be more than enough for most users.

**Comment by Lokathor** [comment]
CI bumped in https://github.com/Lokathor/tinyvec/pull/179

should update the readme or other docs so I'll leave this open still.
