### ISSUE TITLE
when array to vec: use double array size as capacity

### ISSUE THREAD

**Issue by kzhui125** [Lokathor/tinyvec#190]
```rs
let mut chars = tiny_vec!([char; 4]);
chars.extend(['1', '2', '3']);
dbg!(chars.capacity());

let mut chars = vec![' ', ' ', ' ', ' '];
chars.extend(['1', '2', '3']);
dbg!(chars.capacity());
```

maybe it's better to use double array size as capacity?

**Comment by Lokathor** [comment]
The expression `tiny_vec!([char; 4])` has no way to extract the "4" and double it.

Also, An ArrayVec, which a TinyVec uses internally, has a fixed capacity set by the type. Even if it were possible to get the "4" and double it, the output value would be a different type than what the user asked for (every different array length is a different type), which would confuse a lot of people.

So, I don't think we can do this one.
