### ISSUE TITLE
retain_mut

### ISSUE THREAD

**Issue by Fuuzetsu** [Lokathor/tinyvec#195]
A `retain_mut` function would be very useful. There's one for std::vec::Vec: https://doc.rust-lang.org/std/vec/struct.Vec.html#method.retain_mut . It's more efficient to use this than to do two loops of modifying the contents and then checking with `retain` what to remove based on some condition.

I _think_ there's no technical limitation for not having this?

**Comment by Lokathor** [comment]
That function is *relatively* new is all. Most of this crate was made in like the 1.40-ish era iirc, so newer Vec methods aren't always present.

I'm happy to merge a PR that adds this method.
