### ISSUE TITLE
New release to bring the Arbitrary impl to stable Rust

### ISSUE THREAD

**Issue by maoe** [Lokathor/tinyvec#196]
I'd like to use the Arbitrary impl with the stable compiler. Would it be possible to make a new release?

**Comment by Lokathor** [comment]
I'm not sure I understand. The docs.rs page for version 1.6 shows that it already has Arbitrary as a dependency. https://github.com/Lokathor/tinyvec/tree/6e326cc48208229d1f28abf74a3e06944c8f7bec also shows that the arbitrary crate was part of the 1.6 release.

**Comment by maoe** [comment]
Yeah it's in the dependencies but the Arbitrary impl for ArrayVec is behind the nightly_const_generics flag: https://github.com/Lokathor/tinyvec/blob/6e326cc48208229d1f28abf74a3e06944c8f7bec/src/arrayvec.rs#L219-L233

This feature gate has been removed in #180.

**Comment by Lokathor** [comment]
Closed by https://github.com/Lokathor/tinyvec/commit/612c87d0d799b98c662ca44943b6531120d2168b, `tinyvec-1.6.1` should be live.

**Comment by maoe** [comment]
Thank you for the quick turnaround!
