### ISSUE TITLE
impl Debug and Display

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/tinyvec#2]
The derived debug won't know how to pick the inner variant and then display it appropriately, so we'll have to do that by hand.

Also we want to derive Display here because honestly it's always good to have Display.

**Comment by Lokathor** [comment]
Done in 0.1

**Comment by Shnatsel** [comment]
`Vec<T>` doesn't implement `Display`, so why does `TinyVec`?

**Comment by Lokathor** [comment]
three reasons:
1) the std library designers are wrong. they just are, you'll never convince me that not being able to display a vec is somehow a feature.
2) you don't have to use this display impl, anyone is free to use the structure to display in some other way exactly as if the impl didn't exist.
3) No one else is allowed to write this impl even if I don't because of the Orphan Rule, so I'm not cutting off anyone else's possibilities.
