### ISSUE TITLE
Rename ArrayVec to InlineVec.

### ISSUE THREAD

**Issue by engstad** [Lokathor/tinyvec#21]
You wrote it yourself, calling the ArrayVec an "inline" array. :-)

**Comment by repnop** [comment]
I'd argue the new name doesn't add anything of value and might make it more confusing to people looking at the crate for the first time

**Comment by Lokathor** [comment]
Discussing it with a few others, I've given up on bothering with a rename. ArrayVec fits it the most, the name clash is just too bad.

**Comment by c410-f3r** [comment]
For one project, I use `arrayvec::ArrayVec` and the name ambiguity of `tinyvec::ArrayVec` makes it really annoying to work with both.
Can't you reconsider renaming `tinyvec::ArrayVec` to something else like TinyStatic or the one suggested in this PR?

**Comment by Lokathor** [comment]
I think if you are actually using both `arrayvec::ArrayVec` and `tinyvec::ArrayVec` then my advice is to use an alias for one of them.

Unfortunately that's a pretty rare situation, and the current users most voted (on the Rust Community Discord) to keep the name `ArrayVec` when this issue was open.

**Comment by Lokathor** [comment]
```rust
pub type TinyArray<T> = tinyvec::ArrayVec<T>;
```
would do the trick.

**Comment by c410-f3r** [comment]
This is unfortunate. Aliasing might be good for internal usage but I actually export types based on the underlying storage and anything different from the original structure name will probably confuse users.

This use-case is indeed rare. Well, thanks for your answer

**Comment by Lokathor** [comment]
If you also export the type alias then people will also see fields as the aliased name.
