### ISSUE TITLE
ArrayVec::push could have better panic message

### ISSUE THREAD

**Issue by ThatsNoMoon** [Lokathor/tinyvec#24]
[ArrayVec::push](https://github.com/Lokathor/tinyvec/blob/66c99e290bcb352e84d0658ffee02b7270d2458d/src/arrayvec.rs#L364) currently has a pretty barebones panic message on overflow.
```rust
panic!("ArrayVec: overflow!")
```
This might be hard to diagnose, especially without a backtrace, and a more descriptive error message can't hurt. Perhaps something like `"ArrayVec::push overflowed capacity!"` would be better.

**Comment by Lokathor** [comment]
Yeah, changed to `panic!("ArrayVec::push> capacity overflow!")`
