### ISSUE TITLE
TinyVec::capacity returns a static value for vectors with dynamic capacity

### ISSUE THREAD

**Issue by ThatsNoMoon** [Lokathor/tinyvec#26]
[TinyVec::capacity](https://github.com/Lokathor/tinyvec/blob/66c99e290bcb352e84d0658ffee02b7270d2458d/src/tinyvec.rs#L176) always returns `A::CAPACITY`, even when it is a heap-backed array with a dynamic capacity.

**Comment by Lokathor** [comment]
:ferrisSweat:
