### ISSUE TITLE
`ArrayVec::retain` is inefficient

### ISSUE THREAD

**Issue by HeroicKatora** [Lokathor/tinyvec#27]
The method loops like this:

```rust
  while i < self.len {
      if !acceptable(&self[i]) {
        self.remove(i);
      } else {
          i += 1;
      }
   }
```

Note that it calls `remove` within the loop. This itself modifies the length and moves all other items. Removing all items with this strategy is thus `O(n²)`. ~~Furthermore, the indexing gets corrupted as  soon as the first item is removed as `i += 1` is executed even when all further items were shifted backwards one element thus skipping over an element.~~ Missed that this was fixed in 66c99e290bcb352e84d0658ffee02b7270d2458d

**Comment by Lokathor** [comment]
Yeah this was one of the biggest efficiency offenders.

Happy to accept a PR that fixes this one.
