### ISSUE TITLE
`ArrayVec::remove` can unexpectedly return an element

### ISSUE THREAD

**Issue by HeroicKatora** [Lokathor/tinyvec#28]
Calling `remove` with the length of the vector does not panic but instead it returns a defaulted element and forgets about the proper last element.

```rust
let mut av: ArrayVec<[i32; 1]> = Default::default();
av.push(1);
av.remove(1);
// Did not panic.
```

**Comment by Shnatsel** [comment]
Nice find! This method is already covered with fuzzing, but this issue was not found due to https://github.com/jakubadamw/arbitrary-model-tests/issues/2.
