### ISSUE TITLE
`ArrayVec` impl of `Extend` is strange

### ISSUE THREAD

**Issue by HeroicKatora** [Lokathor/tinyvec#31]
I wouldn't have expected an impl of it, similar to how there is no impl of `FromIterator` for arrays.
Maybe for fixed length iterators it would make sense since the caller can check if there is enough space, and avoid the panic.
But `Extend` and `FromIterator` do not offer making this restriction to the passed-in iterator type.
An alternate interface would be to fill the vector as far as possible and returns the remaining iterator.

**Comment by Lokathor** [comment]
I think that:

1) The slight but significant difference between a normal array and an ArrayVec (namely that the ArrayVec can be "partly empty") makes all the difference as to appropriate traits or not.

2) The lack of array support has always been a bad part of Rust and I see no reason to allow it to continue.

3) Doing something like try_extend as an extension method behind a cargo flag would probably work

**Comment by HeroicKatora** [comment]
Alternative, safe interface:

```
fn fill<I>(&mut self, iter: I) -> I::IntoIter
    where I: IntoIterator<Item=T>
{
    let mut iter = iter.into_iter();
    for item in iter.by_ref().take(self.capacity() - self.len()) {
        self.push(item);
    }
    iter
}
```

**Comment by Shnatsel** [comment]
I second that, implementation of `extend()` sounds like a footgun.

ArrayVec crate actually makes [its `extend()`](https://docs.rs/arrayvec/0.5.1/arrayvec/struct.ArrayVec.html#method.extend) ignore any extra elements instead of panicking, which IMO is not a great idea.

Could we remove the `extend()` iml for now or put it behind an unstable API feature flag?

**Comment by Lokathor** [comment]
Throwing this to t-libs to resolve: https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Extend.3A.3Aextend

**Comment by Shnatsel** [comment]
t-libs has ruled that panicking is the better option, which is what TinyVec implements. Closing.
