### ISSUE TITLE
`remove_item`

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/tinyvec#49]
* [ ] ArrayVec
* [ ] TinyVec

Waiting on https://github.com/rust-lang/rust/issues/40062, but we could add it behind a cargo feature until then.

**Comment by saethlin** [comment]
`Vec::remove_item` was deprecated in Rust 1.46. Should this still be implemented?

**Comment by Lokathor** [comment]
Oops, no.

Uh, guess this will just sit there in 1.0, and get removed in 2.0

**Comment by Lokathor** [comment]
Oh we never even added it in the first place!

I'll just close this then.
