### ISSUE TITLE
Use doc attributes on items so that generated rustdoc is better.

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/tinyvec#59]
eg: `#[cfg_attr(docsrs, doc(cfg(feature = "io-std")))]`

We might not even need to use the `docsrs` part, since i don't think it hurts to have the doc attribute on at all times.

**Comment by Nemo157** [comment]
The reason for limiting the attribute like that is that `doc(cfg)` is still unstable (and has some issues that really need to be fixed before it will likely be stabilized).

**Comment by Nemo157** [comment]
(Note for anyone implementing this, you need to add the `docsrs` cfg flag to the `docs.rs` metadata section to enable it, [here's an example](https://github.com/Nemo157/async-compression/blob/c879f434481be47e1da648d217f8842069730943/Cargo.toml#L16)).
