### ISSUE TITLE
crates.io description is very brief

### ISSUE THREAD

**Issue by Shnatsel** [Lokathor/tinyvec#67]
docs.rs provides a very good overview of TinyVec. However, it is the only resource to do so; crates.io or github README are more likely to be discovered first and do not provide a good description of the crate.

We should get a better description for TinyVec at least on crates.io

**Comment by Lokathor** [comment]
personally I always got to docs.rs first, but if someone want to make a better description for crates.io that would be fine

**Comment by anderejd** [comment]
Maybe this could be useful: https://crates.io/crates/cargo-sync-readme
