### ISSUE TITLE
Consider supporting non-Default types by wrapping them in an Option

### ISSUE THREAD

**Issue by Shnatsel** [Lokathor/tinyvec#70]
[It has been pointed out](https://www.reddit.com/r/rust/comments/fshuhk/introducing_tinyvec_100_safe_alternative_to/fm3y9gu/) that it's possible to remove the `T: Default` requirement by wrapping the underlying value in an `Option`.

The runtime cost of this should not be debilitating because a correct implementation should never try to unwrap `Option::None`, and branches that lead to a panic are hinted as cold, so the branch predictor will be able to eliminate most of the cost.

However, it would be a shame to regress the surprisingly good performance that we already have for `T: Default`, so this might require some kind of specialization. Specialization techniques that work on stable have been devised recently, see e.g. https://github.com/dtolnay/case-studies/blob/master/autoref-specialization/README.md

**Comment by HeroicKatora** [comment]
How much mental overhead would it be to offer a wrapper that makes this choice explicit instead of relying on specialization here? That way, the main implementation would not be impacted.

```rust
struct OptionVec<T> {
    inner: TinyVec<Option<T>>,
}
/// Implementation in terms of `T`, not `Option<T>` as `TinyVec`.
impl<T> OptionVec<T> {
}
```

**Comment by RazrFalcon** [comment]
Isn't adding a 1 byte per value is too much of an overhead for a stack-based array?

**Comment by Lokathor** [comment]
I would accept a PR for this as a newtype or alternative type, but the main ArrayVec type will definitely just stick with needing Default. Enough types already support Default, after all.

**Comment by Shnatsel** [comment]
> Isn't adding a 1 byte per value is too much of an overhead for a stack-based array?

This is partially negated by niche optimizations, e.g. if you're storing `Option<&T>` or `Option<&mut T>`.

However, someone else [pointed out](https://www.reddit.com/r/rust/comments/fshuhk/introducing_tinyvec_100_safe_alternative_to/fm4ez9o/) that if the internal values were wrapped as `Option<T>`, there would be no way to slice the data as `[T]`, which is a rather significant limitation - now we're stuck with branching twice on every single access. I expect this will kill performance, so I'm closing this issue as not feasible.

**Comment by Lokathor** [comment]
(did you mean to close it?)

**Comment by Shnatsel** [comment]
Yes. Feel free to reopen if I was too hasty.

**Comment by Lokathor** [comment]
Naw, you're right, it'd be impossible to slice
