### ISSUE TITLE
Error inferring array type when using tiny_vec! with variables

### ISSUE THREAD

**Issue by ThatsNoMoon** [Lokathor/tinyvec#75]
Adding this test:
```rust
#[test]
fn TinyVec_macro_variables_inference() {
  let x = 4i32;
  let y = 5i32;
  let _: TinyVec<[i32; 10]> = tiny_vec!(x, y);
}
```
Produces this error:
```
error[E0435]: attempt to use a non-constant value in a constant
   --> tests\tinyvec.rs:108:41
    |
108 |   let _: TinyVec<[i32; 10]> = tiny_vec!(x, y);
    |                                         ^ non-constant value
```
I believe `x` is assumed to be a const generic parameter, or some such.

**Comment by rodrimati1992** [comment]
From trying this code, what is happening is that it's invoking the
`($array_type:ty, $($elem:expr),* $(,)?) => {` branch of the macro,and passing `x` as a generic parameter.

**Comment by ThatsNoMoon** [comment]
I agree, but from the error message, I don't think it's being passed as a type parameter, but a const parameter.

**Comment by rodrimati1992** [comment]
It's being passed as a generic parameter,which is wrong regardless of whether it's a type parameter or a const parameter.
The problem is if the first element is parseable as a type, then it gets passed as the element type of the remaining elements by the macro.

**Comment by Lokathor** [comment]
So, would a good fix just be to change the macro, so it'd be like `=>` or some other not-comma tokens between the type and the initial values?

That seems simplest to me.
