### ISSUE TITLE
Consider MIR OR Apache2.0 licence

### ISSUE THREAD

**Issue by matklad** [Lokathor/tinyvec#79]
tinyvec is using zlib license, and it is the only crate with this license in rust-analyzer dependency graph. There's some reluctance to including non MIT/Apache licensed code in rust-tooling:

https://github.com/rust-lang/rust/blob/c724b67e1b474262917a5154d74e7072267593fe/src/tools/tidy/src/deps.rs#L22-L25

For example, miniz oxide recently replaced adler32 with alder crate, primarily to remove zlib license.

**Comment by Lokathor** [comment]
Can do. I should have done this sooner really.

I'll try to start a PR later today. Hopefully it shouldn't take too long to get the sign offs.

**Comment by Lokathor** [comment]
To be clear, the crate would move to `Zlib OR Apache-2.0 OR MIT`.

Zlib is essentially strictly superior to MIT for the user.

Also, the point of the adler crate over the adler32 crate is that adler runs several times faster, not really anything to do with license stuff.

**Comment by matklad** [comment]
Might be a good idea to actually change `license =` in Cargo.toml :)

**Comment by Lokathor** [comment]
oh boy XD

fixed

**Comment by Nemo157** [comment]
Also, should include the `LICENSE-*` files in the repo :wink:

**Comment by Lokathor** [comment]
Well I've been told by @JoshTripplet that since the MIT license says to include "the license text" you got in your own distribution, if there's **no** license text included you can just do nothing and be in compliance of the license. So it simplifies the task for the end user to not have a license file at all.
