### ISSUE TITLE
Version bump to rustc 1.40

### ISSUE THREAD

**Issue by Soveu** [Lokathor/tinyvec#88]
Related to #87 
Currently as we implement more std Vec's interface, the version is limiting what we could write.

`DoubleEndedIterator::nth_back` - became stable in 1.37
`Vec::append` (for faster append() when both TinyVecs are on heap) - 1.40

I see there three solutions:
* Just bump the version to 1.40 (_could_ be breaking)
* Gate it behind `rustc-ge-1-40` feature and mark functions with `#[cfg(feature = "rustc-ge-1-40")]`
* Do the reverse, create `compatibility` feature, make it the default and mark functions that require rustc > 1.36 with
`cfg(not(feature = "compatibility"))`

As 0.4 just began to exist and nobody is using it yet, the first solution should work.
Plus, as I mention in #87 there are some bugs in iterators, so _maybe_ we could yank 0.4.0 anyway.

**Comment by Lokathor** [comment]
Bumping the minimum rust version is unacceptable for this crate, unless it's required to fix a soundness hole. Even then I'd release it as a breaking change.

However, some strategy to opt-in to a newer minimum rust version is needed. Currently there's some systems in the works for `cfg` to be able to detect if items are available, or what the current rust version is, or things like that. Until then, we're on our own.

I think that the second option is the simplest: We make a feature (off by default) that indicates that you've opted into a higher rust version. Then when that feature is on we use methods that are stabilized in higher versions and also we implement those methods on our own vecs as necessary.

**Comment by Lokathor** [comment]
The crate now has a `rustc_1_40` feature, closing.
