### ISSUE TITLE
Move all CI to GitHub Actions and make it better

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/tinyvec#90]
Right now the CI is spread across both appveyor and travisCI, despite the crate not being tied to the OS at all.
* We should move to just using GitHub Actions

Also the CI is currently for 1.36.0, Stable, and Nightly, with the spread of what's tested under what toolchain being kinda "whatever"
* We should test our core features under 1.36.0
* We should also test under Stable, Beta, and Nightly
* If a feature *can* be tested on a specific toolchain version then we should do so. Eg: nightly features need Nightly, but `rustc_1_40` requires Stable or later, etc.

**Comment by Shnatsel** [comment]
I will not have the time for this in the near future, sorry.

**Comment by Lokathor** [comment]
Completed in 8453395794c67a271687523b649a9b39b79b6fde
