### ISSUE TITLE
Change type of ArrayVec's len to u8/u16

### ISSUE THREAD

**Issue by Soveu** [Lokathor/tinyvec#94]
```rust
pub struct ArrayVec<A: Array> {
  len: usize,
  pub(crate) data: A,
}
```
I think that `usize` here is a bit of overkill, because
* stack space is very limited (few megabytes)
* moving these huge arrays is costly anyway

Changing it to `u16` or `u8` could make this structure a bit smaller
(btw why is `ArrayVec` `repr(C)`?)

**Comment by Lokathor** [comment]
I can easily imagine wanting an arrayvec bigger than 256 elements, so u8 is out, but u16 *might be* a sane option.

However, I don't know that saving 2 bytes is a big deal.

**Comment by Soveu** [comment]
Not only 2 bytes, also it can change the alignment

**Comment by Soveu** [comment]
*slaps the roof*
ArrayVec with u16 len can fit so many bytes in it
[rust playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1b27f91aa0509ebd16c5cc2e0b892cd4)

**Comment by Shnatsel** [comment]
I was initially skeptical as well, but accounting for alignment it does appear to be worthwhile. Those 48 bytes vs 32 bytes cases do look impressive.

**Comment by Lokathor** [comment]
I'm convinced enough.

This is technically an ever so slight break.

I'd be willing to make this change in the transition from 0.4 to 1.0. That's August 27th (next rust release).

One important detail is that len operations should still take place in the usize type as much as possible. It sounds dumb but it's slightly more efficient to have ops be done using the CPU's native register size.

**Comment by Shnatsel** [comment]
Let's do a fuzzing run before releasing 1.0 so that we catch the overflows such as https://github.com/rust-lang/rust/issues/72237

**Comment by Lokathor** [comment]
yeah we can fuzz main

**Comment by Lokathor** [comment]
@Soveu I'm declaring that you've got until the 13th to have it all set. That's 2 weeks for code changes, and then 2 weeks for fuzzing and finalization.

**Comment by Soveu** [comment]
With the current implementation we can manually limit the max array size of `u16::MAX`, but on const generics we can't declare N as u16
```rust
struct ArrayVec<T, const N: u16> {
  len: u16,
  data: [T; N], // <- N must be usize, [T; N as usize] does not work
}
```
Maybe it is worth filing an issue on rustc github

**Comment by Soveu** [comment]
Even checks like [this](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=91ea8f65c7c7340f0cc36207b57a83da) don't work :/

**Comment by Lokathor** [comment]
big oof

**Comment by Lokathor** [comment]
I'll ask on zulip if this will be in the min_const_generics.

in general, i think that 1.0 will be minimum rust 1.34 and basically not support const generics that well, if at all, and then once const generics are properly stable, we'll do a 2.0 version some day with a sufficiently higher minimum rust version.
